// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {v1} from '../models';

export function DeletePod(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetAvailableContexts():Promise<Array<string>>;

export function GetConfigMaps(arg1:string,arg2:string):Promise<backend.ConfigMapListDTO>;

export function GetDaemonSets(arg1:string,arg2:string):Promise<backend.DaemonSetListDTO>;

export function GetDeployments(arg1:string,arg2:string):Promise<backend.DeploymentListDTO>;

export function GetNamespaces(arg1:string):Promise<backend.NamespaceListDTO>;

export function GetPersistentVolumeClaims(arg1:string,arg2:string):Promise<backend.PersistentVolumeClaimListDTO>;

export function GetPersistentVolumes(arg1:string):Promise<backend.PersistentVolumeListDTO>;

export function GetPodEvents(arg1:string,arg2:string,arg3:string):Promise<backend.EventListDTO>;

export function GetPodLogs(arg1:backend.PodLogsRequest):Promise<Array<string>|string>;

export function GetPodMetrics(arg1:string,arg2:string,arg3:string):Promise<backend.PodMetricsDTO>;

export function GetPods(arg1:string,arg2:string):Promise<backend.PodListDTO>;

export function GetPodsByDeployment(arg1:string,arg2:string,arg3:v1.LabelSelector):Promise<backend.PodListDTO>;

export function GetResourceYaml(arg1:backend.GetResourceYamlRequest):Promise<string>;

export function GetSecrets(arg1:string,arg2:string):Promise<backend.SecretListDTO>;

export function GetServices(arg1:string,arg2:string):Promise<backend.ServiceListDTO>;

export function GetStatefulSets(arg1:string,arg2:string):Promise<backend.StatefulSetListDTO>;

export function ListPodMetrics(arg1:string,arg2:string):Promise<backend.PodMetricsListDTO>;

export function RestartDeployment(arg1:string,arg2:string,arg3:string):Promise<boolean>;
