// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';
import {backend} from '../models';

export function GetAvailableContexts():Promise<Array<string>>;

export function GetConfigMaps(arg1:string,arg2:string):Promise<v1.ConfigMapList>;

export function GetDaemonSets(arg1:string,arg2:string):Promise<v1.DaemonSetList>;

export function GetDeployments(arg1:string,arg2:string):Promise<v1.DeploymentList>;

export function GetNamespaces(arg1:string):Promise<v1.NamespaceList>;

export function GetPersistentVolumeClaims(arg1:string,arg2:string):Promise<v1.PersistentVolumeClaimList>;

export function GetPersistentVolumes(arg1:string):Promise<v1.PersistentVolumeList>;

export function GetPodLogs(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<string>|string>;

export function GetPods(arg1:string,arg2:string):Promise<v1.PodList>;

export function GetPodsByDeployment(arg1:string,arg2:string,arg3:v1.LabelSelector):Promise<v1.PodList>;

export function GetResourceYaml(arg1:backend.GetResourceYamlRequest):Promise<string>;

export function GetSecrets(arg1:string,arg2:string):Promise<v1.SecretList>;

export function GetServices(arg1:string,arg2:string):Promise<v1.ServiceList>;

export function GetStatefulSets(arg1:string,arg2:string):Promise<v1.StatefulSetList>;

export function RestartDeployment(arg1:string,arg2:string,arg3:string):Promise<boolean>;
