// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableContexts() {
  return window['go']['main']['App']['GetAvailableContexts']();
}

export function GetConfigMaps(arg1, arg2) {
  return window['go']['main']['App']['GetConfigMaps'](arg1, arg2);
}

export function GetDaemonSets(arg1, arg2) {
  return window['go']['main']['App']['GetDaemonSets'](arg1, arg2);
}

export function GetDeployments(arg1, arg2) {
  return window['go']['main']['App']['GetDeployments'](arg1, arg2);
}

export function GetNamespaces(arg1) {
  return window['go']['main']['App']['GetNamespaces'](arg1);
}

export function GetPersistentVolumeClaims(arg1, arg2) {
  return window['go']['main']['App']['GetPersistentVolumeClaims'](arg1, arg2);
}

export function GetPersistentVolumes(arg1) {
  return window['go']['main']['App']['GetPersistentVolumes'](arg1);
}

export function GetPods(arg1, arg2) {
  return window['go']['main']['App']['GetPods'](arg1, arg2);
}

export function GetSecrets(arg1, arg2) {
  return window['go']['main']['App']['GetSecrets'](arg1, arg2);
}

export function GetServiceYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetServiceYaml'](arg1, arg2, arg3);
}

export function GetServices(arg1, arg2) {
  return window['go']['main']['App']['GetServices'](arg1, arg2);
}

export function GetStatefulSets(arg1, arg2) {
  return window['go']['main']['App']['GetStatefulSets'](arg1, arg2);
}
